services:
  tumor-api:
    image: spedros/tumor-api
    container_name: tumor-api
    ports:
    - "5000:5000"
    restart: always
  mlops-tumor-web:
    image: spedros/mlops-tumor-web
    container_name: mlops-tumor-web
    ports:
    - "8501:8501"
    environment:
    - API_URL=http://tumor-api:5000/predict
    depends_on:
    - tumor-api
    restart: always
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-tumor
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-tumor
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
    - prometheus
    volumes:
    - grafana-storage:/var/lib/grafana
    - ./grafana-provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  grafana-storage: